# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "raulkite's blog"
description: > # this means to ignore newlines until "email:"
   Learning and travelling

email: raul@um.es
#blog logo
logo: "/assets/images/koala.jpg"
# blog cover
cover: "/assets/images/minimized.jpg"

name: 'raulkite'
author: 'Raul Sanchez'
author_image: "/assets/images/turtle.jpg"

paginate:	5

url: "http://raulkite.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@ra_garu'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ra_garu
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/raulkite
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
#

future: true
